Repository pagopa/pagopa-fdr-2-event-hub, pull requests merged in 2025-02, with the labels that each got.

#2 feat: Add identity and gha
  .github/workflows/anchore.yml
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_code.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
Labels: skip, size/large, ignore-for-release

#10 fix: [PAGOPA-2682] Opening port 8080 for `HTTP-Trigger`ed function
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: bug

#9 feat: [PAGOPA-2619] - HTTP recovery function
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/model/BlobFileData.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtil.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/wrapper/BlobServiceClientWrapper.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/wrapper/BlobServiceClientWrapperImpl.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunctionTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunctionTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtilTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/util/SampleContentFileUtil.java
Labels: enhancement, size/large, major
