Repository pagopa/pagopa-fdr-2-event-hub, pull requests merged in 2025-04, with the labels that each got.

#21 fix: [PAGOPA-2852] Resolving memory leak on FdR1BlobProcessing function
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/parser/FDR1XmlSAXParser.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/parser/FDR1XmlStAXParser.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/parser/FlussoRendicontazioneTagParser.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/parser/FlussoRiversamentoTagParser.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtil.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunctionTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunctionTest.java
Labels: bug, size/large, patch

#22 fix: Slack notification
  .github/workflows/release_deploy.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
Labels: size/small

#24 [PAGOPA-2987] chore: Add AlertAppException
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpMassiveBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/exception/AlertAppException.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/exception/EventHubException.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/exception/XmlParsingException.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtil.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunctionTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunctionTest.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/HttpMassiveBlobRecoveryFunctionTest.java
Labels: enhancement, size/large, patch
