Repository pagopa/pagopa-fdr-2-event-hub, pull requests merged in 2025-03, with the labels that each got.

#12 fix(ENV): Add `hostid` for Storage Queue name definition
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: bug, size/small, patch

#11 [PAGOPA-2686] opex: Add error-codes
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtil.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/ErrorCodes.java
Labels: size/small

#13 Update values-uat.yaml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: size/small

#14 [PAGOPA-2686] fix(util): Update parse date method
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/mapper/FlussoRendicontazioneMapper.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/util/FlussoRendicontazioneMapperTest.java
Labels: size/small

#15 fix: [PIDM-360] Resolving bug on payment event send for QI
  .github/workflows/code_review.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/fdr/to/eventhub/BlobProcessingFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
  src/main/java/it/gov/pagopa/fdr/to/eventhub/util/CommonUtil.java
  src/test/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunctionTest.java
Labels: bug, patch

#16 feat: [PAGOPA-2473] Define new github token
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/01_github_environment.tf
  .identity/99_main.tf
Labels: skip, size/small

#18 feat: [PAGOPA-2620] Including handling of FdR3 files on HTTP trigger
  src/main/java/it/gov/pagopa/fdr/to/eventhub/HttpBlobRecoveryFunction.java
Labels: enhancement
